owner: riscstar
repo: dashboard

sites:
  - name: Main website
    url: https://riscstar.com
  - name: Main website 404 page
    url: https://riscstar.com/404
    expectedStatusCodes:
      - 404

  - name: Releases toolchain page
    url: https://releases.riscstar.com/toolchain/

  - name: Community forum about page
    url: https://forums.riscstar.com/about
  - name: Community forum 404 page
    url: https://forums.riscstar.com/404
    expectedStatusCodes:
      - 404
  
  - name: People for Jonathan S Tuttle
    url: https://people.riscstar.com/~jonathan/
  - name: People 404 page
    url: https://people.riscstar.com/~404/
    expectedStatusCodes:
      - 404

status-website:
  baseUrl: /dashboard
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dashboard
  introTitle: "**RISCstar** website availability dashboard."
  introMessage: This provides a short status summary of the availability of RISCstar web services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
