owner: riscstar
repo: dashboard

# See https://upptime.js.org/docs/configuration for configuration docs.

sites:
  - name: Main website
    url: https://riscstar.com
  - name: Main website 404 page
    url: https://riscstar.com/404
    expectedStatusCodes:
      - 404

  - name: Releases toolchain page
    url: https://releases.riscstar.com/toolchain/

  - name: Community forum about page
    url: https://forums.riscstar.com/about
  - name: Community forum 404 page
    url: https://forums.riscstar.com/404
    expectedStatusCodes:
      - 404

  - name: People for Jonathan S Tuttle
    url: https://people.riscstar.com/~jonathan/public/
  - name: People 401 page
    url: https://people.riscstar.com/~jonathan/
    expectedStatusCodes:
      - 401

status-website:
  baseUrl: /dashboard
  name: RISCstar Dashboard
  logoUrl: https://raw.githubusercontent.com/riscstar/dashboard/refs/heads/master/assets/riscstar-icon.png
  introTitle: "**RISCstar** website availability dashboard."
  introMessage: This provides a short status summary of the availability of RISCstar web services.
  # We can't have a robots.txt since this website isn't the top-level domain.
  # This is the best we can do to discourage indexing.
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Home page
      href: https://riscstar.com
    - title: Status
      href: /dashboard
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/20 * * * *"
