owner: riscstar
repo: dashboard

sites:
  - name: Main website
    url: https://riscstar.com
  - name: Releases website
    url: https://releases.riscstar.com
  - name: Community forum front page
    url: https://forums.riscstar.com
  - name: People front page
    url: https://people.riscstar.com
  - name: People for Jonathan S Tuttle
    url: https://people.riscstar.com/~jonathan/

status-website:
  baseUrl: /dashboard
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Dashboard
  introTitle: "**RISCstar** website availability dashboard."
  introMessage: This provides a short status summary of the availability of RISCstar web services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
